version: "3"
services:

  app:
    build: app
    ports:
      - '80:8080'
    volumes:
      - ./app/deployments:/opt/jboss/wildfly/standalone/deployments

  endo:
    build: endo
    ports:
      - '90:8080'
