version: "3"
services:

  app:
    build: app
    ports:
      - '80:8080'
    volumes:
      - ./app/deployments:/opt/jboss/wildfly/standalone/deployments

  endo:
    build: endo
    ports:
      - '90:8080'
    volumes:
      - ./endo/deployments:/opt/jboss/wildfly/standalone/deployments

  users:
    build: users
    ports:
      - '100:8080'
    volumes:
      - ./users/deployments:/opt/jboss/wildfly/standalone/deployments

  quests:
    build: quests
    ports:
      - '110:8080'
    volumes:
      - ./quests/deployments:/opt/jboss/wildfly/standalone/deployments

  shop:
    build: shop
    ports:
      - '120:8080'
    volumes:
      - ./shop/deployments:/opt/jboss/wildfly/standalone/deployments

  reward:
    build: reward
    ports:
      - '130:8080'
    volumes:
      - ./reward/deployments:/opt/jboss/wildfly/standalone/deployments

  db:
    image: mariadb:10.1.18
    ports:
      - '3306:3306'
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      LANG: C.UTF-8
      MYSQL_DATABASE: test
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
